#!/bin/bash
#docker run --privileged -i -v /proc:/proc \
#    -v ${PWD}:/working_dir \
#    -w /working_dir \
#    debian:latest \
#    /bin/bash -s etc/terraform.conf < build.sh

docker run --privileged -i -v /proc:/proc \
    -v ${PWD}:/working_dir \
    -w /working_dir \
    debian:bookworm \
    /bin/bash -s etc/terraform.conf < build.sh
